napp/urls.py
from django.urls import path
from napp import views

app_name="napp"

urlpatterns = [
    path('',views.home,name='home'),
    path('register/',views.register,name="register"),

]

userdemo1/urls.py
from django.contrib import admin
from django.urls import path,include
import napp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('napp.urls')),
]

napp/models.py
from django.db import models

# Create your models here.

napp/forms.py
from django.contrib.auth.models import User
from django import forms

class UserRegistration(forms.ModelForm):
    password=forms.CharField( max_length=15, required=True,Widget=forms.PasswordInput),
    class Meta:
        model=User
        fields=('first_name','last_name','username','email','password')

napp/views.py
from django.shortcuts import render
from napp import forms

# Create your views here.
def home(request):
    return render(request,'napp/home.html')

def register(request):
    if request.method=="POST":
        password=request.POST.get('password')
        userform=forms.UserRegistration(request.POST)
        if userform.is_valid():
            user=userform.save(commit=False)
            user.set_password(password)
            user.save()
    form=forms.UserRegistration()
    return render(request,'napp/register.html',{'form':form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        <title>Document</title>
    {% endblock %}
    
    
    
</head>
<body>

    <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'napp:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'napp:register' %}">Register</a>
        </li>
        
      </ul>
      {% block content %}
        

      {% endblock %}
    
</body>
</html>

templates/napp/home.html
{% extends "base.html" %}

{% block title %}
    <title> UserDemo | Homepage</title>
{% endblock %}


{% block content %}
    <div class="jumbotron">
            <h1>Welcome to homepage</h1>
    </div>
{% endblock %}

templates/napp/register.html
{% extends "base.html" %}

{% block title %}
    <title> UserDemo | Homepage</title>
{% endblock %}


{% block content %}
    <div class="jumbotron">
            <form  method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="register" class='btn btn-primary'>

            </form>
    </div>
{% endblock %}